### ISSUE TITLE
Incorrect autodoc links for fkm_nonlinear

### ISSUE THREAD

**Issue by johannes-mueller** [boschresearch/pylife#56]
The functions referenced in `docs/strength/fkm_nonlinear` are not found.

```
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylife.strength.fkm_nonlinear
>>> pylife.strength.fkm_nonlinear.perform_fkm_nonlinear_assessment
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pylife.strength.fkm_nonlinear' has no attribute 'perform_fkm_nonlinear_assessment'
>>> pylife.strength.fkm_nonlinear.for_material_group
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pylife.strength.fkm_nonlinear' has no attribute 'for_material_group'
>>>
```

**Comment by maierbn** [comment]
Fixed in #59
